import { z } from "zod";
import { ProtocolVersionSchema } from "./version";

/**
 * Server → client envelope: { v, roomId, seq, ts, type, payload }.
 *
 * `seq` increases monotonically per room. Clients apply events in seq
 * order and drop anything at or below the last seq they have applied,
 * which makes delivery idempotent.
 */
export const EventEnvelopeBaseSchema = z.object({
  v: ProtocolVersionSchema,
  roomId: z.string().min(1).max(64),
  seq: z.number().int().positive(),
  /** Server time, epoch ms. */
  ts: z.number().int().nonnegative(),
});

export function defineEvent<T extends string, P extends z.ZodType>(type: T, payload: P) {
  return EventEnvelopeBaseSchema.extend({ type: z.literal(type), payload });
}

/**
 * Client → server command: { v, type, clientMsgId, payload }.
 *
 * `clientMsgId` is generated by the client per command and reused on
 * retry, so the server can acknowledge a duplicate without re-running it.
 */
export const CommandEnvelopeBaseSchema = z.object({
  v: ProtocolVersionSchema,
  clientMsgId: z
    .string()
    .min(8)
    .max(64)
    .regex(/^[A-Za-z0-9_-]+$/, "Invalid clientMsgId"),
});

export function defineCommand<T extends string, P extends z.ZodType>(type: T, payload: P) {
  return CommandEnvelopeBaseSchema.extend({ type: z.literal(type), payload });
}
